package com.zomato.order_service.enums;

public enum OrderStatus {
    PENDING,PLACED, CONFIRMED, PREPARING, READY_FOR_PICKUP, ASSIGNED_TO_RIDER,
    PICKED_UP, OUT_FOR_DELIVERY, DELIVERED, CANCELLED, FAILED
}
