spring.application.name=mail-service
server.port=8086

#Kafka
customer.topic.name=customer
rider.topic.name=rider
restaurant.topic.name=restaurant
password.change.topic.name=passwordChange
topic.invoice.name=invoice
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.type.mapping=MailDto:com.zomato.mail_service.dto.MailDto
spring.kafka.consumer.group-id=mail-service-group
spring.kafka.consumer.properties.fetch.max.bytes=20971520
spring.kafka.consumer.properties.max.partition.fetch.bytes=20971520



#Mailer
spring.mail.host=smtp.zoho.in
spring.mail.port=587
spring.mail.username=nutrimatrix@zohomail.in
spring.mail.password=fR0rHbJpMEWK
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


email.from=nutrimatrix@zohomail.in

#Mongo
spring.data.mongodb.uri=mongodb+srv://rootuser:Jaibholeki1%40@zomato-mail.uziojbv.mongodb.net/NUTRIMATRIX?retryWrites=true&w=majority
