spring.application.name=payment-service
server.port=8085

razorpay.key=rzp_test_RebBBdTECe8S1P
razorpay.secret=x18y1MZSE4gOzbKQ01THXjGC



#Kafka
payment.topic.name=payment
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=1
spring.kafka.producer.properties.spring.json.type.mapping=OrderPaymentDto:com.zomato.payment_service.dto.OrderPaymentDto



# Driver class name
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Zomato
spring.datasource.username=root
spring.datasource.password=Jaibholeki1@


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

