spring.application.name=order-service
server.port=8088

# Driver class name
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Zomato
spring.datasource.username=root
spring.datasource.password=Jaibholeki1@

################

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT
jwt.secret.key=77uhhdfeug73373@@^#%$&(*hcdhhb```!!"""";;;;12


#constants
platform.fee=10


#Kafka:for fetching payment status from payment service
payment.webhook.topic=payment-webhook-details
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.type.mapping=OrderPaymentDto:com.zomato.order_service.dto.kafka.payment.OrderPaymentDto

#producer for sending mail
delivery.confirmation.topic=customer-delivery-confirmation
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=MailDto:com.zomato.order_service.dto.kafka.mail.MailDto
spring.kafka.producer.acks=1
