spring.application.name=invoice-service
server.port=8090


customer.acknowledgement.topic=order-acknowledgement
rider.acknowledgement.topic=rider-acknowledgement
restaurant.acknowledgement.topic=restaurant-acknowledgement

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=1
spring.kafka.producer.properties.spring.json.type.mapping=MailDto:com.zomato.invoice_service.dto.mail.MailDto
spring.kafka.producer.properties.max.request.size=20971520
